"""
Reporting and file output tools.
"""
import os
import re
from datetime import datetime
from core.config import CURRENT_SESSION_DIR, logger, get_current_session_reports_dir

def generate_vuln_report(
    target_ip: str,
    vulnerability_name: str,
    exploit_steps: str,
    severity: str = "High",
    cve_id: str = "N/A",
    mitigation: str = "Pending investigation"
) -> str:
    """
    Generates or appends to a formal Markdown vulnerability report for a specific target.
    Includes severity, PoC commands, and a session-wide summary index.
    """
    # 1. Validation
    if not target_ip or not vulnerability_name or not exploit_steps:
        error_msg = "[ERROR] Missing required fields: target_ip, vulnerability_name, or exploit_steps."
        logger.error(error_msg)
        return error_msg
    
    # Strict IP / Hostname format validation
    ip_pattern = r"^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$"
    if not re.match(ip_pattern, target_ip) and not re.match(r"^[a-zA-Z0-9.-]+$", target_ip):
        error_msg = f"[ERROR] Invalid target IP address or hostname format: {target_ip}"
        logger.warning(error_msg)
        return error_msg

    # 2. Path Setup
    report_dir = get_current_session_reports_dir()
    
    report_file = os.path.join(report_dir, f"audit_{target_ip.replace('.', '_')}.md")
    summary_file = os.path.join(CURRENT_SESSION_DIR, "session_summary.md")
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # 3. Severity Emojis for Visual Clarity
    sev_map = {
        "Critical": "💀 CRITICAL",
        "High": "🔴 HIGH",
        "Medium": "🟠 MEDIUM",
        "Low": "🟡 LOW",
        "Informational": "🔵 INFO"
    }
    sev_display = sev_map.get(severity, f"⚪ {severity}")
    
    # 4. Format detailed report entry
    report_entry = f"## {sev_display}: {vulnerability_name}\n"
    report_entry += f"- **Target:** {target_ip}\n"
    report_entry += f"- **Discovery Date:** {timestamp}\n"
    report_entry += f"- **CVE Reference:** {cve_id}\n\n"
    report_entry += f"### Proof of Concept / Exploit Chain\n"
    report_entry += f"The following command sequence confirms the vulnerability:\n"
    report_entry += f"```bash\n{exploit_steps}\n```\n\n"
    report_entry += f"### Recommended Mitigation\n"
    report_entry += f"{mitigation}\n\n"
    report_entry += "---\n\n"
    
    try:
        # Write to Per-IP Audit Report
        is_new_report = not os.path.exists(report_file)
        with open(report_file, 'a', encoding='utf-8') as f:
            if is_new_report:
                f.write(f"# Audit Report: {target_ip}\n")
                f.write(f"> Generated by Autonomous Framework | Session: {os.path.basename(CURRENT_SESSION_DIR)}\n\n---\n\n")
            f.write(report_entry)
            
        # Write to Session Summary Index
        is_new_summary = not os.path.exists(summary_file)
        with open(summary_file, 'a', encoding='utf-8') as f:
            if is_new_summary:
                f.write("# Strategic Campaign Summary\n\n")
                f.write("| Severity | Target | Finding | Detailed Report |\n")
                f.write("| :--- | :--- | :--- | :--- |\n")
            
            # Add table row
            f.write(f"| {severity} | `{target_ip}` | {vulnerability_name} | [View Audit Log](reports/audit_{target_ip.replace('.', '_')}.md) |\n")
            
        logger.info(f"Vulnerability report updated for {target_ip}: {vulnerability_name}")
        return f"[SUCCESS] Vulnerability '{vulnerability_name}' ({severity}) documented in reports."
        
    except Exception as e:
        logger.exception(f"Failed to generate report: {e}")
        return f"[ERROR] Failed to write report: {e}"
